version: '2'

services:
  node_staging:
    container_name: react-practice
    image: node:6
    ports:
      - "4500:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/bash -c "npm install &&  npm run dev"
